name: Build & Publish to GitHub Pages

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main
        
    - name: Set up Node environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install modules
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Write CNAME
      run: echo "explorer.barnabycollins.com" > dist/CNAME
    
    - name: Deploy to gh-pages branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SQUASH_HISTORY: true
        MESSAGE: Build commit {sha} ("{msg}")

